def user_data_dir(appname: str = None, appauthor: str = None, version: str = None, roaming: bool = False) -> str: ...
def site_data_dir(appname: str = None, appauthor: str = None, version: str = None, multipath: bool = False) -> str: ...
def user_config_dir(appname: str = None, appauthor: str = None, version: str = None, roaming: bool = False) -> str: ...
def site_config_dir(appname: str = None, appauthor: str = None, version: str = None, multipath: bool = False) -> str: ...
def user_cache_dir(appname: str = None, appauthor: str = None, version: str = None, opinion: bool = True) -> str: ...
def user_log_dir(appname: str = None, appauthor: str = None, version: str = None, opinion:bool = True) -> str: ...

class AppDirs(object):
    def __init__(self, appname: str, appauthor: str = None, version: str = None, roaming: bool = False,
                 multipath: bool = False) -> None: ...
    @property
    def user_data_dir(self) -> str: ...
    @property
    def site_data_dir(self) -> str: ...
    @property
    def user_config_dir(self) -> str: ...
    @property
    def site_config_dir(self) -> str: ...
    @property
    def user_cache_dir(self) -> str: ...
    @property
    def user_log_dir(self) -> str: ...
